python-graphblas/python-graphblas

- grblas/exceptions.py
- grblas/monoid/numpy.py
- grblas/ops.py
- grblas/semiring/numpy.py
- grblas/unary/numpy.py
- test/test_numpyops.py
- test/test_op.py
This follows one of @seibert suggestions of casting the result back to `bool`.  I think the final solution makes sense, but it was an adventure of surprises to get there.  Score one for persistence.
> Fix bool monoids

- grblas/exceptions.py
- grblas/matrix.py
- grblas/monoid/numpy.py
- grblas/ops.py
- grblas/scalar.py
- grblas/semiring/numpy.py
- grblas/unary/numpy.py
- grblas/vector.py
- test/test_matrix.py
- test/test_numpyops.py
- test/test_op.py
- test/test_scalar.py
Note that this continues from https://github.com/jim22k/grblas/pull/14 .  Sorry for the chain of dependent PRs.  I separated them since each may have particular things to discuss.
> Scalar isequal isclose

- .travis.yml
- README.md
- test/test_numpyops.py
- test/test_vector.py
Also, test Python 3.7 and 3.8.
Also, add a couple tests for complex UDFs.
> Add build status badge from TravisCI

- grblas/__init__.py
- test/test_resolving.py
Fixes https://github.com/jim22k/grblas/issues/30
Also added a test for sanity.
> Auto-import dtypes and others as appropriate.

- .travis.yml
- README.md
- setup.cfg
While we're at it, let's add some conda-forge badges too!
> This runs coverage and adds a badge.

- grblas/base.py
- grblas/matrix.py
- grblas/vector.py
- test/test_matrix.py
The fix is simple and pragmatic.
I still have half a mind to do some refactoring, but that may need to wait until we wrap another implementation!
> This fixes a bug where temporaries were being garbage-collected too early

- grblas/base.py
- grblas/matrix.py
- grblas/vector.py
- test/test_matrix.py
- test/test_scalar.py
- test/test_vector.py
Fixes https://github.com/jim22k/grblas/issues/28
My bad for not testing this better last time!  I got things backwards.
> Fix reduce with scalar and accum (again)

- grblas/__init__.py
- grblas/base.py
- grblas/formatting.py
- grblas/io.py
- grblas/mask.py
- grblas/matrix.py
- grblas/ops.py
- grblas/vector.py
- test/test_numpyops.py
- test/test_op.py
- test/test_vector.py
Notably, if a grblas Matrix or Vector is very large, we will grab only parts of it to put in pandas DataFrame. Hence, the pandas DataFrame doesn't need to match the dimensions the grblas object!  This is much better.
There is still more I would like to do with repr, but this seems like a good step! I still need to update the notebook and add some tests (preferably after some feedback).
> Create better repr and repr_html.  Use pandas if available.

- README.md
- recipe/meta.yaml
- setup.py
We still need to grant permission for coveralls.io to work.
> Change github org from `jim22k` to `metagraph-dev`

- .travis.yml
- grblas/__init__.py
- grblas/matrix.py
- grblas/scalar.py
- grblas/tests/test_resolving.py
- grblas/vector.py
I still need to test this locally, but this approach should work.
I set "no cover" to the `pygraphblas` code sections, b/c I have no idea how we're going to test it in travis-ci.
> Add basic support for to/from pygraphblas by adding it as a backend

- binder/environment.yml
This can give users a live notebook to interact with!
I think I'll want to play around with this a bit more before we link to a binder instance.
> Add an environment for binder

- .travis.yml
- grblas/backends/suitesparse/build.py
- grblas/backends/suitesparse/suitesparse_graphblas_3.3.3.h
- grblas/tests/test_core.py
- grblas/tests/test_resolving.py
Also, add a regression test that makes sures the header file versions match.
> Use SS:GraphBLAS header 3.3.3.  Oops.

- .travis.yml
- conftest.py
- grblas/__init__.py
- grblas/base.py
- grblas/descriptor.py
- grblas/dtypes.py
- grblas/expr.py
- grblas/formatting.py
- grblas/mask.py
- grblas/matrix.py
- grblas/ops.py
- grblas/recorder.py
- grblas/scalar.py
- grblas/tests/conftest.py
- grblas/tests/test_descriptor.py
- grblas/tests/test_dtype.py
- grblas/tests/test_matrix.py
- grblas/tests/test_recorder.py
- grblas/vector.py
Every non-None argument to a GraphBLAS call needs to be wrapped by a Python object to be recorded.  This is now done for most things.  We should aspire to use `call` instead of `check_status`, since the recorder hook will be in `call`.
We can get the backend call with a utility function such as:
```python
def gbstr(x):
if x is None:
return "NULL"
elif isinstance(x, TypedOpBase):
name = x.gb_name
elif isinstance(x, Mask):
name = x.mask.name
elif type(x) is TransposedMatrix:
name = x._matrix.name
else:
name = x.name
if not name:
return f"temp_{type(x).__name__.lower()}"
return name
```
<details>
<summary>Examples (from running the tests)</summary>
```C
GrB_Matrix_assign_INT64(temp_matrix, A_1, NULL, s_assign, GrB_ALL, 1, GrB_ALL, 5, GrB_DESC_S)
GrB_Matrix_assign_INT64(temp_matrix, A_1, …
```
> Get ready for recording GraphBLAS calls.

- grblas/backends/suitesparse/clean_header.py
- grblas/backends/suitesparse/suitesparse_graphblas_no_complex_4.0.3.h
- grblas/dtypes.py
- grblas/ops.py
- grblas/tests/test_numpyops.py
- grblas/tests/test_op.py
Turns out removing support for complex numbers is tricky. Lots of assumptions baked into the code and tests about these being present.
> Fixes to fully remove support for complex from grblas

- grblas/__init__.py
- grblas/base.py
- grblas/tests/test_core.py
- grblas/tests/test_resolving.py
- grblas/tests/test_scalar.py
- grblas/tests/test_vector.py
> Experiment with `replace` singleton: `C(mask, replace) << A.mxm(B)`

- grblas/io.py
- grblas/tests/test_io.py
b/c sometimes these can have duplicates.
> Support `dup_op=` when converting from scipy.sparse and MatrixMarket

- grblas/recorder.py
Using contextvars probably isn't worth the hassle, but this has been educational.
Testing this is pretty tricky.
> The recorder is giving me issues in Jupyter again, so here's a fix.

- .github/workflows/test_and_build.yml
- grblas/_ss/matrix.py
- grblas/_ss/vector.py
- grblas/tests/test_matrix.py
- grblas/tests/test_vector.py
- recipe/meta.yaml
- setup.py
> Update to SuiteSparse:GraphBLAS 5.1.3

- grblas/expr.py
- grblas/tests/test_infix.py
In particular, I have found myself wanting to do `(A @ B).new()`.
> Add `.new()` method to infix expressions.

- .github/workflows/debug.yml
> Add debug workflow to enable ssh to debug!

- grblas/_ss/matrix.py
- grblas/_ss/utils.py
- grblas/_ss/vector.py
- grblas/recorder.py
- grblas/tests/test_matrix.py
- grblas/tests/test_recorder.py
- notebooks/Aggregators.ipynb
Also `flatten_columns` of course!
We could also spell this as `matrix.ss.flatten()`, but then what do we use as arguments?
TODO: add the inverse operation to go from Vector to Matrix
> Add `matrix.ss.flatten_rows` to flatten a Matrix to a Vector row-wise.

- grblas/formatting.py
- grblas/tests/test_formatting.py
Previously, actual nan values got replaced by '' in the reprs.
> Display nan values in reprs.

- .github/workflows/test_and_build.yml
- grblas/__init__.py
This bug was breaking deserialization of Matrix objects.  `sys.meta_path` ftw!
> Fix e.g. `import grblas.matrix` when done before `grblas.init` is called

- grblas/expr.py
- grblas/tests/test_vector.py
I think this is worth the little-bit of overhead that it costs.
> Support negative indices as per normal Python/NumPy rules

- .github/workflows/test_and_build.yml
- grblas/_automethods.py
- grblas/_infixmethods.py
- grblas/infix.py
- grblas/matrix.py
- grblas/scalar.py
- grblas/utils.py
- grblas/vector.py
and `python -m grblas._infixmethods`.  Fixes #155.
This was pretty quick, low-tech, and surprisingly fun!
> Auto-generate code via e.g. `python -m grblas._automethods`

- .github/workflows/test_and_build.yml
- conftest.py
- grblas/base.py
- grblas/dtypes.py
- grblas/expr.py
- grblas/io.py
- grblas/monoid/numpy.py
- grblas/operator.py
- grblas/scalar.py
- grblas/tests/conftest.py
- grblas/tests/test_dtype.py
- grblas/tests/test_io.py
- grblas/tests/test_numpyops.py
- grblas/tests/test_op.py
- grblas/tests/test_operator_types.py
- grblas/tests/test_scalar.py
- grblas/tests/test_vector.py
- grblas/unary/numpy.py
- notebooks/Operators.ipynb
Also, don't show chained/nested exceptions when unnecessary.
> Investigate #184 by running on more OSes.

- .github/workflows/test_and_build.yml
This seems like a pretty good trick for testing robustness 🤞
> Re-add `pytest-randomly` to CI.  Things have been stable.

- graphblas/operator.py
- graphblas/tests/test_op.py
> Allow e.g. `gb.binary.register_new` to create UDFs

- graphblas/_automethods.py
- graphblas/_infixmethods.py
- scripts/autogenerate.py
- scripts/bizarro_scalars.sh
- scripts/create_pickle.py
- scripts/test_imports.sh
- setup.cfg
The goal is to make like easier for developers/contributors.  These should probably be mentioned in our contributor guide (TODO).
- autogenerate.py
- Runs `python -m graphblas._automethods` and `python -m graphblas._infixmethods`
- bizarro_scalars.sh
- Changes default scalars (used when testing in CI)
- create_pickle.py
- Create the pickle files used in testing
- test_imports.sh
- Import all the things one-by-one
> Add scripts to help developers/contributors

- README.md
- graphblas/exceptions.py
- setup.py
I think all the new links work.
> Finish renaming metagraph-dev to python-graphblas

- graphblas/_agg.py
- graphblas/_ss/config.py
- graphblas/_ss/descriptor.py
- graphblas/_ss/matrix.py
- graphblas/_ss/vector.py
- graphblas/ss/__init__.py
- graphblas/ss/_core.py
- graphblas/tests/test_matrix.py
- graphblas/tests/test_ss_utils.py
- graphblas/tests/test_vector.py
Some of the code is a little hairy, but I think it gives a pretty good user experience.
> Add `ss.config` to manage SuiteSparse:GraphBLAS config options

- .github/workflows/publish_pypi.yml
Closes #175.  Probably.  We'll know for sure next release!
> github action to auto-upload releases to PyPI

- .github/workflows/publish_pypi.yml
- graphblas/tests/test_numpyops.py
I wonder why this is needed now?  I've used this GA elsewhere without needing to install wheel.  Meh.
> pip install wheel before building wheel

- graphblas/__init__.py
- graphblas/io.py
- graphblas/viz.py
- scripts/test_imports.sh
- setup.cfg
One uses matplotlib `spy` and one uses datashader via hvplot.  Both are pretty!
These are meant to be opinionated and easy to use with reasonable defaults, but with "enough" flexibility to allow for some customization.  They're also meant to show off :)
matplotlib:
datashader via hvplot:
Some nice things about using datashader:
- interactive!
- able to use different aggregators
- able to view the _values_
- able to compose and link multiple plots together
-  could be useful for e.g. viewing both arguments to a function
> WIP: Begin adding viz functions for viewing sparse matrix

- .pre-commit-config.yaml
Also, add hook to ensure we don't accidentally commit to main branch.
> Update pre-commit hooks and make them fail fast

- .pre-commit-config.yaml
- graphblas/core/formatting.py
- graphblas/core/matrix.py
- graphblas/core/scalar.py
- graphblas/core/vector.py
- graphblas/tests/test_formatting.py
> Don't show format of expr in repr (to match behavior of HTML repr)

- graphblas/core/expr.py
- graphblas/core/formatting.py
- graphblas/core/matrix.py
- graphblas/core/operator.py
- graphblas/monoid/numpy.py
I'm a little surprised our linters didn't catch these.
> Remove unnecessary fstring

- graphblas/core/matrix.py
- graphblas/core/ss/matrix.py
- graphblas/core/vector.py
- graphblas/tests/test_matrix.py
- setup.py
> Expose `GxB_pack_HyperHash` and `GxB_unpack_HyperHash`

- graphblas/core/ss/matrix.py
- graphblas/core/ss/vector.py
> Improve `.ss.head` by using GxB iterators

- binder/environment.yml
Closes #317. Probably.
Should we add `hvplot` and `datashader` too, or wait until we have notebooks showing off the viz using them?
> Update binder environment

- README.md
- setup.py
Also added some helpful links to the top of the REAME
> Add a badge to README for discord chat

- .github/workflows/test_and_build.yml
I'm having occasional issues with coveralls
> Add codecov for coverage reporting

- .github/workflows/test_and_build.yml
- graphblas/core/ss/vector.py
> Try using mamba instead of conda in CI

- README.md
> Add DOI from Zenodo to README

- setup.py
I like this explanation: https://martin-thoma.com/software-development-stages/#5-productionstable
I think `python-graphblas` is stable enough to reliably use and ready for production.
@jim22k do you concur?
> Update "Development Status" classifier to "Production/Stable"

- graphblas/core/matrix.py
- graphblas/core/vector.py
This allows us to apply a mask during the recipe.
I forgot to do this in https://github.com/python-graphblas/python-graphblas/pull/307
> Make vanilla `ewise_union` into an expression recipe

- .pre-commit-config.yaml
- environment.yml
- graphblas/tests/conftest.py
- setup.cfg
This is one step towards the contributor guide.
CC @SultanOrazbayev, who may find `environment.yml` helpful.
> Add environment.yml to create dev environment

- environment.yml
`ipykernel` -  useful when working with jupyterlab and `nb_conda_kernels`;
`sparse` - useful for io.
> Add `ipykernel` and `sparse`

- .github/workflows/imports.yml
- .github/workflows/lint.yml
- .github/workflows/test_and_build.yml
My hope is that this will make CI a little bit faster, since `./scripts/test_imports.sh` is pretty slow.
This also tests a minimal set up and install with pip.
> New Github Action for testing imports

- .github/workflows/test_and_build.yml
- .pre-commit-config.yaml
#354 handles style checks now, so might as well make main testing CI  focus on tests and coverage instead of style.
> Remove style checks from main CI tests; rely on pre-commit

- graphblas/core/matrix.py
- graphblas/core/vector.py
- graphblas/tests/test_matrix.py
- graphblas/tests/test_vector.py
As first discussed here: https://github.com/python-graphblas/python-graphblas/issues/372#issuecomment-1398727757
> Use default values of 1.0 for `from_*` methods of Vector and Matrix

- .pre-commit-config.yaml
- docs/conf.py
- graphblas/__init__.py
- graphblas/core/automethods.py
- graphblas/core/infixmethods.py
- graphblas/core/utils.py
- graphblas/tests/conftest.py
- graphblas/tests/test_dtype.py
- graphblas/tests/test_matrix.py
- graphblas/tests/test_pickle.py
- graphblas/tests/test_prefix_scan.py
- graphblas/tests/test_vector.py
- pyproject.toml
- scripts/create_pickle.py
I don't think Numba supports these yet in compiled functions, since numba uses its own RNG.
> Use `np.random.default_rng` instead of legacy functions

- .github/workflows/test_and_build.yml
- graphblas/tests/test_numpyops.py
oops, I used the wrong names in #393
> Fix complex arcsin test on Windows

- docs/user_guide/operations.rst
Closes #434. Also, fixed two examples.
It would still be nice to set up doctest at some point.
> Create output objects in operations.rst examples

- MANIFEST.in
- README.md
Oops. Maybe I should have done an alpha-release first.
> Use external link for images in README (to show up on PyPI)

- .github/workflows/test_and_build.yml
- .pre-commit-config.yaml
- README.md
- docs/getting_started/primer.rst
- docs/user_guide/init.rst
- docs/user_guide/operations.rst
- docs/user_guide/operators.rst
- docs/user_guide/recorder.rst
- docs/user_guide/udf.rst
- graphblas/core/matrix.py
- graphblas/viz.py
- pyproject.toml
This doesn't actually add `blacken-docs` as pre-commit hook. `blacken-docs` doesn't like when we sometimes use `>>>` in code blocks, and it doesn't like how we align the code comments in the README.
Also, do a few misc changes pointed out by https://scikit-hep.org/developer/reporeview
> blacken docs (and other misc)

- .github/workflows/test_and_build.yml
- .pre-commit-config.yaml
- graphblas/tests/test_vector.py
- scripts/check_versions.sh
> Don't install graphblas=8.0 yet

- .github/workflows/test_and_build.yml
- graphblas/dtypes.py
- graphblas/tests/test_io.py
- pyproject.toml
- scripts/check_versions.sh
Fixes #463
Looks like pytest started picking up the configuration from `python-graphblas`.
> Fix testing fix_test_suitesparse_graphblas

- LICENSE
- docs/conf.py
This is like how Dask and Bokeh handle this. @jim22k I'd like your explicit approval.
> Update copyright to include contributors

- README.md
As requested here: https://github.com/pyOpenSci/software-submission/issues/81#issuecomment-1635687588
> Add pyopensci badge to README

- .github/workflows/test_and_build.yml
- .pre-commit-config.yaml
- graphblas/exceptions.py
- pyproject.toml
- scripts/check_versions.sh
A bit of maintenance to ensure we are testing with the latest versions of pandas and awkward.
> MAINT: update versions of pandas, awkward, and pre-commit linting

- graphblas/tests/test_io.py
I added support for numpy 1.26 in #493, but missed this change 🤞
> Try to fix failing test

- .github/workflows/test_and_build.yml
- CODE_OF_CONDUCT.md
- LICENSE
- README.md
- docs/make.bat
- notebooks/Example B.1 -- Level BFS.ipynb
- notebooks/Example B.3 -- Parent BFS.ipynb
Also:
- update a few `http:` links to `https:`
- show calendar invite is also at https://scientific-python.org/calendars/
> Test against python-suitesparse-graphblas 8.2.1.0 in CI

- .pre-commit-config.yaml
- graphblas/core/operator/utils.py
- graphblas/tests/test_scalar.py
- graphblas/tests/test_vector.py
- scripts/check_versions.sh
This should fix https://github.com/python-graphblas/graphblas-algorithms/issues/82
Also, update pre-commit versions while (b/c why not?).
> Fix the return type of e.g. `agg.count` to be INT64 by default
