.gitignore
.travis.yml

Jim, you'll need log in to https://travis-ci.org/ and enable CI for this repo (under Settings->Repositories I think).
This isn't quite working yet.  `python setup.py build_ext` or `pip install -e .` fail.  See: https://travis-ci.org/github/eriknw/grblas/jobs/663215948

Add simple .travis.yml for CI testing

---

grblas/__init__.py
grblas/binary/__init__.py
grblas/monoid/__init__.py
grblas/ops.py
grblas/semiring/__init__.py
grblas/unary/__init__.py

This better leverages the import system.  The previous approach is pretty fragile.
I tested this with the following commands (many of which previously failed):
```bash
python -c 'from grblas import lib'
python -c 'from grblas import ffi'
python -c 'from grblas import base'
python -c 'from grblas.base import IndexerResolver'
python -c 'from grblas import descriptor'
python -c 'from grblas.descriptor import lookup'
python -c 'from grblas import dtypes'
python -c 'from grblas.dtypes import unify'
python -c 'from grblas import exceptions'
python -c 'from grblas.exceptions import check_status'
python -c 'from grblas import io'
python -c 'from grblas.io import to_scipy_sparse_matrix'
python -c 'from grblas import mask'
python -c 'from grblas.mask import ComplementedValueMask'
python -c 'from …
```

A better way to handle auto-initialization and imports.

---

grblas/base.py
grblas/exceptions.py
grblas/matrix.py
grblas/monoid/numpy.py
grblas/ops.py
grblas/semiring/numpy.py
grblas/unary/numpy.py
grblas/vector.py
test/test_matrix.py
test/test_numpyops.py
test/test_op.py
test/test_vector.py

When registering new unary or binary ops, use `parameterized=True` argument.  Monoids and semirings are implicitly parameterized if an input binaryop or monoid are parameterized.
This PR continued from https://github.com/jim22k/grblas/pull/13, so probably merge that one first.

Parameterized udfs

---

grblas/base.py
grblas/io.py
grblas/mask.py
grblas/matrix.py
grblas/scalar.py
grblas/vector.py
test/test_matrix.py

Don't subclass TransposedMatrix from Matrix.  It's not really a GbContainer.  This led to surprising things to be possible.
Instead of blacklisting methods that don't work, choose to be positive and add the ones that do.  I hope this will make it harder to make mistakes in the future.
I took the liberty of moving `is_scalar` and `is_transposed` to private properties.
This PR continues from: https://github.com/jim22k/grblas/pull/15

Fix transposed matrix

---

grblas/base.py
grblas/dtypes.py
grblas/exceptions.py
grblas/matrix.py
grblas/ops.py
grblas/scalar.py
grblas/unary/numpy.py
grblas/vector.py
test/test_dtype.py
test/test_matrix.py
test/test_numpyops.py
test/test_op.py
test/test_scalar.py
test/test_vector.py

This began by wanting to use the numba-compiled UDF for scalar `isclose`.
This resulted in paying down technical debt.
We no longer rely on weird global state, and some operations are more specific.

Create `TypedOp` classes for more flexibility.

---

grblas/base.py
grblas/matrix.py
grblas/scalar.py
grblas/vector.py
test/test_matrix.py
test/test_resolving.py
test/test_scalar.py
test/test_vector.py

This PR continues from https://github.com/jim22k/grblas/pull/19 to avoid merge conflict.
Scalar reductions are able to specify the result dtype:
- `v.reduce().new(dtype=float)`
Simple scalar update works:
- `s << t`
- `s << 1`
Scalar update with extract element works:
- `s << v[1]`
More explicit error messages were given for edge cases that don't work.

More flexible and explicit handling of scalar update

---

conftest.py
grblas/tests/conftest.py

We need the top-level conftest.py for reasons, but this isn't currently available
when we test `grblas` when it's been installed.  So, let's move a couple pytest
setup functions to grblas/tests/conftest.py.  I don't know if this is considered
best practice, but it seems to check all the boxes for what I want.
When testing locally, we still have our nice options like --runslow and --nonblocking,
but when testing installed, we only test blocking suitesparse, and we don't skip slow.

Run `grblas.init` when testing installed version of grblas.

---

.travis.yml
grblas/dtypes.py
grblas/expr.py
grblas/matrix.py
grblas/tests/test_matrix.py
grblas/tests/test_numpyops.py
grblas/tests/test_vector.py
grblas/vector.py

Make `to_values` return a tuple of numpy arrays.
Make `from_values` and `build` accept numpy arrays as input.
Add "size" option to build, allowing it to function as a more effective rebuild.
Significant speed improvement for large objects.
```python
import numpy as np
import grblas
ni = np.arange(100000)
nv = np.ones(100000)
li = ni.tolist()
lv = nv.tolist()
vec = grblas.Vector.from_values(li, lv)
vec = grblas.Vector.from_values(ni, nv)
```
Exporting using `to_values()` has a similar speedup.
Note that `from_values` with list or tuple input actually slowed down with the new code. I put in additional checks for datatypes.

`to_values` returns numpy array

---

grblas/__init__.py
grblas/base.py
grblas/exceptions.py
grblas/expr.py
grblas/mask.py
grblas/matrix.py
grblas/scalar.py
grblas/tests/conftest.py
grblas/tests/test_core.py
grblas/tests/test_formatting.py
grblas/tests/test_matrix.py
grblas/tests/test_op.py
grblas/tests/test_recorder.py
grblas/tests/test_resolving.py
grblas/tests/test_scalar.py
grblas/tests/test_vector.py
grblas/vector.py

Things became much simpler after introducing `Assigner`, which is the result of `C[I, J](Mask)` and `C(Mask)[I, J]` operations.  This was previously handled by `AmbiguousAssignOrExtract`.
This introduces SuiteSparse-specific functionality, and I note this in the code where appropriate.  The only recipes I needed to create were for assigning scalars for subassign to matrix row or column.
I flesh out some tests that were missing, such as `C(mask)[I, j] << v`.
I'm relying on CI to see if any notebooks need updated 🤞 
Oh, I should probably add something to the documentation (`README.md`).

Support subassign with expected syntax `C[I, J](Mask) << A`

---

grblas/io.py
grblas/tests/test_io.py

These are simply wrappers around `scipy.io.{mmread,mmwrite}`.  I haven't given this much thought, and I'm not intimately familiar with the Matrix Market format.
It's very possible we could use other libraries to read/write Matrix Market files, such as LAGraph.  But, offering something--or someday *many* things--in `grblas` is very convenient.

io.mmread and io.mmwrite for Matrix Market files

---

grblas/backends/suitesparse/build.py
setup.py

These may be necessary on some systems to find "GraphBLAS.h", and it shouldn't hurt to add if they aren't necessary.

Include `sys.prefix / "include"` in `include_dirs` when building extensions

---

setup.py

I don't know if we should also do this if the platform is "cygwin".
Also, I don't want to worry about cross-platform compilation yet.

Include DLLs when building on Windows.

---

grblas/operator.py
grblas/tests/test_op.py

Testing also revealed that `plus_land` is a strange GxB semiring: `land` always return BOOL, so it must get cast the the input type when doing `plus`.
Closes #77.

Rename `div` to `cdiv` in semirings and add `truediv` and `floordiv` semirings

---

grblas/base.py
grblas/matrix.py
grblas/scalar.py
grblas/tests/test_recorder.py
grblas/vector.py

If the name of a scalar is falsey, it will instead use the value of the scalar as the name.

Use `name=""` when creating scalars in operations to improve recording.

---

grblas/base.py
grblas/expr.py
grblas/matrix.py
grblas/tests/test_matrix.py
grblas/tests/test_vector.py

Instead, use `mask=` keyword in the appropriate operation.
Also, for sanity, don't allow Vector, Matrix, or TransposedMatrix to be converted to numpy arrays.
Heads up: Some array creation semantics are changing in numpy 1.20.

Don't allow expressions with `v[w]`; we don't support boolean maskig like numpy

---

grblas/tests/test_op.py

Changes required to work with the header file from https://github.com/GraphBLAS/python-suitesparse-graphblas/pull/7

Don't use deprecated objects in tests.

---

.github/workflows/test_and_build.yml
grblas/__init__.py
grblas/_ss/matrix.py
grblas/_ss/vector.py
grblas/base.py
grblas/dtypes.py
grblas/exceptions.py
grblas/expr.py
grblas/matrix.py
grblas/operator.py
grblas/recorder.py
grblas/scalar.py
grblas/ss.py
grblas/tests/test_auto_init.py
grblas/tests/test_dtype.py
grblas/tests/test_matrix.py
grblas/tests/test_op.py
grblas/tests/test_operator_types.py
grblas/tests/test_pygraphblas.py
grblas/tests/test_recorder.py
grblas/tests/test_scalar.py
grblas/tests/test_vector.py
grblas/utils.py
grblas/vector.py

- Allow Scalars to be used in indexing
- Allow Scalars to be used to construct numpy arrays
- Fix SuiteSparse bug in Matrix apply1st and apply2nd (but now fixed in SS 5.0.3)
- Fix dtypes.unity for complex numbers (all pairs now match numpy behavior)
- Add sane coercions to operators (such as `exp(1)`)

Update to 5.0.3.  Includes changes that were part of the aggregator branch.

---

grblas/expr.py
grblas/tests/test_vector.py

Add `.value` to `ScalarMatMulExpr` objects

---

grblas/_ss/matrix.py
grblas/_ss/scalar.py
grblas/_ss/vector.py
grblas/matrix.py
grblas/tests/test_matrix.py
grblas/tests/test_vector.py
grblas/vector.py

Not only is it nice to have this alongside other import/export options, it lets us expose additional functionality that SuiteSparse provides:
- is_iso, import/export values array with a single element
- sorting on output
Also, added `x.ss.build_scalar` for GxB_Matrix_build_Scalar and GxB_Vector_build_Scalar.  Finally, accept a scalar for the values in `from_values`.
Note that I changed `sorted_index` to `sorted_rows` and `sorted_cols` for Matrix import/exports.  This lets us distinguish whether COO indices are sorted row-first or column-first.  Vector import/export still uses `sorted_index`.

Add "coo" as import/export option for SuiteSparse.

---

grblas/base.py
grblas/expr.py
grblas/tests/test_infix.py
grblas/tests/test_vector.py

The cached `_value` should be read-only and, hence, valid to return from `.new()`.

Optimization: use cached `_value` `expr.new()` if possible

---

grblas/matrix.py
grblas/tests/test_prefix_scan.py

If we use a backend other than SuiteSparse:GraphBLAS, I expect `_VectorAsMatrix` would copy the data into a Matrix like we were originally doing.

Use `_VectorAsMatrix` in `C(M.S)[row, cols] << v` to avoid copy

---

grblas/_ss/prefix_scan.py
grblas/base.py
grblas/matrix.py
grblas/operator.py
grblas/scalar.py
grblas/tests/test_op.py
grblas/vector.py

@jim22k this was pretty easy to add, and may actually be kinda nice!

Operators may be given as strings in methods: `A.mxm(B, 'min.+[float]')`

---

grblas/_automethods.py
grblas/_infixmethods.py
grblas/infix.py
grblas/matrix.py
grblas/tests/test_matrix.py
grblas/vector.py

Doing `ewise_add` for `xor` is what makes sense.  `xor` is a Monoid with the identity of `False`.

Add xor infix for bools, which performs eadd/union/outer

---

grblas/_agg.py
grblas/_ss/matrix.py
grblas/_ss/vector.py
grblas/base.py
grblas/expr.py
grblas/infix.py
grblas/matrix.py
grblas/operator.py
grblas/scalar.py
grblas/ss/_core.py
grblas/utils.py
grblas/vector.py

I've been annoyed that `dtype=` was keyword-only.

Make `dtype=` an optional positional argument.

---

grblas/_infixmethods.py
grblas/infix.py
grblas/matrix.py
grblas/tests/test_infix.py
grblas/vector.py

Example error message:
```
TypeError: Infix operator __add__ between Vector and Vector is not supported.  This infix operation is only allowed if one of the arguments is a scalar.  We refuse to guess whether you intend to do ewise_mult or ewise_add.
You must indicate ewise_mult (intersection) or ewise_add (union) explicitly.
For ewise_mult:
>>> op.plus(x & y)
or
>>> x.ewise_mult(y, op.plus)
For ewise_add:
>>> op.plus(x | y)
or
>>> x.ewise_add(y, op.plus)
```

Better error message for e.g. `A + B`

---

grblas/_infixmethods.py
grblas/expr.py
grblas/tests/test_infix.py

`x - y` is not yet implemented for non-scalars (we'll use GxB Union).

Support infix between containers.  `x + y` is outer.

---

grblas/base.py
grblas/matrix.py
grblas/vector.py

This can help identify which call in a large expression is causing the error.

Include operator in `expect_type` error message.

---

.github/workflows/test_and_build.yml
grblas/formatting.py
grblas/matrix.py
grblas/scalar.py
grblas/tests/test_formatting.py
grblas/vector.py

Although format such as `csr` is SuiteSparse-specific, this seems useful to show.Hopefully it's not too much of a burden to keep the tests up to date (since SuiteSparse is free to change the underlying formats).
Other changes:
- expressions now show autocomputed results in `__repr__` (not just `_repr_html_`)
- expressions `_repr_html_` collapse the input arguments

Add format to repr and a couple other minor repr changes.

---

grblas/_agg.py
grblas/binary/__init__.py
grblas/binary/numpy.py
grblas/monoid/__init__.py
grblas/monoid/numpy.py
grblas/op/__init__.py
grblas/op/numpy.py
grblas/operator.py
grblas/semiring/__init__.py
grblas/semiring/numpy.py
grblas/tests/conftest.py
grblas/tests/test_op.py
grblas/tests/test_operator_types.py
grblas/unary/__init__.py
grblas/unary/numpy.py

Fixes #130.  CC @ParticularMiner
Now the import time of grblas is dominated by importing pandas, numba, and numpy.  For me, the import time is about 5x faster (hooray!).
This was a bit more complicated than I expected.  I'll give this another pass tomorrow.

Import grblas faster by delaying creation of new ops.

---

grblas/_ss/matrix.py
grblas/_ss/vector.py
grblas/matrix.py
grblas/ss/_core.py
grblas/tests/test_matrix.py
grblas/tests/test_vector.py
grblas/vector.py

When creating a Matrix, a Vector is handled as an Nx1 Matrix.
I still need to update the docstring for usage.
I would also like to add `v.ss.split` for Vectors.
For example:
```python
>>> gb.ss.concat([v, v])  # Vector, size=2*N
>>> gb.ss.concat([[v], [v]])  # Matrix, nrows=2*N, ncols=1
>>> gb.ss.concat([[v, v]])  # Matrix, nrows=N, ncols=2
```

Make `gb.ss.concat` work with vectors!

---

grblas/infix.py
grblas/matrix.py
grblas/scalar.py
grblas/tests/test_matrix.py
grblas/tests/test_scalar.py
grblas/tests/test_vector.py
grblas/vector.py

Very small change that I've been considering for a couple years now.  `x.ndim` is sometimes convenient to write code that works with Scalar, Vector, or Matrix objects.  We've been using `len(x.shape)` fairly often in `dask-grblas`.

Add `.ndim` attribute to objects

---

grblas/base.py
grblas/expr.py
grblas/matrix.py
grblas/tests/conftest.py
grblas/tests/test_formatting.py
grblas/tests/test_infix.py
grblas/tests/test_matrix.py
grblas/tests/test_numpyops.py
grblas/tests/test_op.py
grblas/tests/test_prefix_scan.py
grblas/tests/test_resolving.py
grblas/tests/test_scalar.py
grblas/tests/test_vector.py
grblas/vector.py

Most notably, `dask_grblas` is now able to automatically copy and convert testsfrom `grblas`.  This is important so that `dask-grblas` is able to better match the `grblas` API *and* to stay up to date more easily.  It is the burden of `dask-grblas` developers to ensure `grblas` tests may be copied over.
This entails adding a superfluous (for `grblas`) function `compute` in a few tests. It also includes separating imports of `Matrix`, `Vector`, and `Scalar` so these may be easily imported from `dask_grblas` instead of `grblas`. Finally, I changed some argument names from `delayed` to `expr`, since `delayed` means something else in `dask_grblas`.

A few changes to be more friendly to `dask-grblas`.

---

grblas/__init__.py

Well this is annoying 🤷  (`importlib.abc` isn't available if you only import `importlib`).

Fix importing from `importlib.abc` in Python 3.10

---

grblas/expr.py
grblas/tests/test_resolving.py

This converts the resolved indices back to a valid Python index.  This may be useful when handling indices in `dask-grblas`.
Handling indices is surprisingly annoying!

Add `.py_indices` attribute to `IndexerResolver` objects

---

.github/workflows/test_and_build.yml
grblas/matrix.py
grblas/tests/test_matrix.py
grblas/tests/test_vector.py
grblas/vector.py

We'll want the the dask distributed scheduler to know the size of objects so it can send them around effectively.

Add `.__sizeof__` method to Matrix and Vector objects.

---

.github/workflows/test_and_build.yml
grblas/_slice.py
grblas/_ss/matrix.py
grblas/_ss/prefix_scan.py
grblas/_ss/vector.py
grblas/matrix.py
grblas/tests/test_matrix.py
grblas/tests/test_vector.py
grblas/vector.py

Vectors are still TODO.  We also need tests.
We had previously spec'ed out having `sort=` argument to compactify.
We can still add this, but I don't know if it's really necessary.

Add `.ss.compactify` to Vector and Matrix objects

---

.github/workflows/test_and_build.yml
grblas/_agg.py
grblas/_ss/matrix.py
grblas/base.py
grblas/formatting.py
grblas/matrix.py
grblas/operator.py
grblas/scalar.py
grblas/tests/test_matrix.py
grblas/tests/test_scalar.py
grblas/tests/test_vector.py
grblas/vector.py
notebooks/Example B.1 -- Level BFS.ipynb

Fixes #160
This should be able to speed up some aggregators in `dask-grblas`.

Allow reduce to scalar to result in empty scalar

---

CODE_OF_CONDUCT.md

@seibert @jim22k @paul-tqh-nguyen, since this repo is in the `metagraph-dev` org, I'm volunteering us all to be part of the working group to handle any reported issues (as is done in `metagraph`).  You may remove yourself from this document at any time.
Stan, does the email for this group have my latest email?

Add a code of conduct (copied from metagraph)

---

grblas/base.py
grblas/tests/test_infix.py
grblas/tests/test_vector.py

This was an interesting edge case that I stumbled upon!
Anyway, I think this can also provide better error messages.

Autocompute scalar expressions in `.update` if valid.

---

conftest.py
grblas/binary/__init__.py
grblas/binary/numpy.py
grblas/monoid/__init__.py
grblas/monoid/numpy.py
grblas/op/__init__.py
grblas/op/numpy.py
grblas/operator.py
grblas/semiring/__init__.py
grblas/semiring/numpy.py
grblas/tests/conftest.py
grblas/tests/test_op.py
grblas/tests/test_operator_types.py
grblas/unary/__init__.py
grblas/unary/numpy.py

Also, make sure all commute targets exists (but haven't done this for numpy namespaces yet)

Add `rpow` and improve tab-completion of operator namespaces.

---

grblas/_infixmethods.py
grblas/base.py
grblas/scalar.py
grblas/tests/test_vector.py

This allows `+=` (or any inplace infix that performs outer join) to operate in one C call instead of two.
Pragmatically, this helps one from debating over `x += expr` and `x(plus) << expr`, which now produce the exact same C calls.  This also keeps the original behavior with scalars: `x += 1` is the same as `x << x + 1`,  which only adds 1 to existing entries--it does not "densify" the object.
The only "visible" change for users is that e.g. `x += x + x` will now compute when autocompute is disabled.
Heh, as you probably guessed, this came about b/c I was fretting over `x += expr` and `x(plus) << expr`.  @jim22k which do you consider more idiomatic?  I think I generally prefer `x += expr`.

Make `v += expr` do `v(plus) << expr` when expr is not scalar.

---

grblas/_ss/matrix.py
grblas/_ss/vector.py
grblas/tests/test_matrix.py
grblas/tests/test_vector.py

I think it's nice to capture intent here even though this is currently a recipe.  We could make this faster by e.g. using iterators that SuiteSparse:GraphBLAS recently added.
Some possible alternative behaviors of `x.ss.iso_value`:
- If empty, return empty scalar (it currently raises)
- If not iso-valued, return `None` (it currently raises)

Add `x.ss.iso_value` to Vector and Matrix objects

---

grblas/_infixmethods.py
grblas/infix.py
grblas/matrix.py
grblas/operator.py
grblas/tests/test_infix.py
grblas/tests/test_matrix.py
grblas/tests/test_operator_types.py
grblas/tests/test_vector.py
grblas/vector.py

Fixes #197, and implements nearly everything in the alt proposal.
Supersedes https://github.com/metagraph-dev/grblas/pull/202.
This doesn't perform a faster recipe `C(M.S) << plus(A | v)` -> `C(M.S) << plus(A | any_second(M @ v.diag())`.  Although I think this recipe would be a lot faster and more memory efficient, it's also difficult to implement.

Broadcasting! `plus(A & v)` -> `any_plus(A @ v.diag())`

---

.github/workflows/test_and_build.yml
graphblas/operator.py
graphblas/tests/test_numpyops.py
graphblas/tests/test_op.py
graphblas/tests/test_scalar.py
recipe/meta.yaml
setup.py

Update to latest `python-suitesparse-graphblas` to avoid segfaults 🤞 .
Also, let's see if using `pytest-randomly` works now.

Complex monoid UDFs are finally working!

---

graphblas/operator.py
graphblas/tests/test_op.py

Tiny PR.  This fixes an oversight Jim and I saw while discussing select.

Add `.is_positional` attribute to parameterized operators.

---

graphblas/dtypes.py
graphblas/operator.py
graphblas/tests/test_dtype.py

Also, only have a single object for each `numpy.dtype` for UDTs.  This makes it easier and less awkward for us, but could result in weirdness if the same dtype is registered multiple times under different names.  Probably okay.

Auto-register dtypes as UDTs.

---

graphblas/dtypes.py
graphblas/tests/test_dtype.py

This doesn't have as much detail as numpy or numba typically show,
but we want the default name to be friendlier since it shows up in object reprs.
We still might want to update object reprs to better handle long UDT names.

Better default names for UDTs.

---

graphblas/operator.py
graphblas/tests/test_vector.py

We could do Monoids too if we assumed identity of 0.
This uses the recent work on UDTs to compile only for the dtypes that we need, so it's actually fairly fast.
I think this is actually pretty nice!

Allow lambdas to be passed as UnaryOp and BinaryOp

---

graphblas/operator.py
graphblas/tests/test_op.py
graphblas/tests/test_operator_types.py

This is needed to calculate transitivity of a graph.
This is a "nice" example that shows how to customize creation of UDFs.  On the other hand, it shows how bespoke and sensitive it is to do.
I wonder whether the return type should be `INT64` or `FP64`, since binomial coefficients can get quite large in general.  Or maybe we should add `FP64` to the valid types (input and output).

Add `gb.binary.binom` to compute binomial coefficients.

---

graphblas/matrix.py
graphblas/tests/test_matrix.py
graphblas/tests/test_vector.py
graphblas/vector.py

I find this especially true for Vectors.  SuiteSparse:GraphBLAS often sorts things, but this isn't guaranteed.  So, let's make it explicit, and promise to sort manually for future backends if necessary.

Add `sort=True` keyword to `to_values`.

---

graphblas/formatting.py
graphblas/tests/test_formatting.py

This suggestion came about when demoing `python-graphblas` to @ericmjl (thanks!).

Add `index` and `value` to vector repr

---

graphblas/dtypes.py
graphblas/tests/test_dtype.py

For example, with this, one can use `{'x': int, 'y': float}` as a dtype, which is a lot simpler than `np.dtype([("x", np.int64), ("y", np.float64)])`.  I wonder whether there are any "gotchas" with this.

Allow record dtypes to be created more easily via dicts

---

graphblas/scalar.py
graphblas/tests/test_matrix.py
graphblas/tests/test_scalar.py

I think this makes it a little more convenient when dealing with property graphs.

Allow dicts to be used as scalars for record dtypes.

---

graphblas/__init__.py
graphblas/indexunary/__init__.py
graphblas/matrix.py
graphblas/operator.py
graphblas/tests/test_matrix.py
graphblas/tests/test_vector.py
graphblas/vector.py

- Add IndexUnaryOp and typed versions
- New gb.indexunary namespace
- Apply works with both IndexUnaryOp and SelectOp
- The only real difference is what happens when you call those ops. Passing them to `apply` is treated identically when calling into SuiteSparse.
- Add tests

Make apply accept IndexUnaryOps

---

graphblas/operator.py
graphblas/tests/test_op.py

Although aggregators aren't present in `gb.op`, `gb.op.from_string` often serves to "convert this string to the best operator-like thing".

Have `op.from_string` include aggregators (last priority)

---

graphblas/_agg.py
graphblas/tests/test_matrix.py
graphblas/tests/test_vector.py

By default, reduces argument to scalar, but `rowwise=` or `columnwise=` keyword may be used to reduce to vector.
Closes #238
This *does not* include `allow_empty=` keyword argument, which is available in `reduce` methods when reducing to scalar.  `allow_empty=False` only works on pure Monoid aggregators.  Also, we now have `.get` which makes it easier to get with a default value.

Make aggregators callable.

---

graphblas/__init__.py
graphblas/expr.py
graphblas/mask.py
graphblas/tests/test_core.py
graphblas/tests/test_mask.py
graphblas/utils.py
scripts/test_imports.sh

Largely based on https://github.com/python-graphblas/python-graphblas/issues/234#issuecomment-1132304594
This does not yet make masks "value-y".
Light benchmarking was done to choose "good enough" recipes, but better recipes may exist.  The code is structured in a way that a recipe for any combination of masks may be easily updated.  This will help us improve a specific recipe if it's ever important for a benchmark.
This includes `complement=True` option to return the _complement_ of merged masks.
There have been times when I've wanted to do `.new()` on a mask.
Hopefully the results are intuitive.  I think they are.

Add `mask.new()`, which can merge two masks

---

graphblas/base.py
graphblas/tests/test_matrix.py

Now that SuiteSparse:GraphBLAS has iso-valued objects, I think it's okay to support this syntax.
Also, when reading or writing algorithms, I find that type-ambiguity isn't much of an issue.
So, I don't think the nuisance of raising this exception is worth the benefit anymore.

Allow `A << 1` to create dense matrices.

---

graphblas/base.py
graphblas/binary/numpy.py
graphblas/expr.py
graphblas/mask.py
graphblas/matrix.py
graphblas/operator.py
graphblas/tests/conftest.py
graphblas/tests/test_mask.py
graphblas/tests/test_matrix.py
graphblas/tests/test_numpyops.py
graphblas/tests/test_op.py
graphblas/tests/test_vector.py
graphblas/unary/numpy.py
graphblas/vector.py

Was playing around a bit tonight and came up with this.  Sorry for taking "easier" work if anybody else had designs to implement this!
This is (1) in https://github.com/python-graphblas/python-graphblas/issues/234
An interesting side effect of applying our normal auto-compute rules is this gave `.S` and `.V` to `TransposedMatrix` objects, which required `config.get("autocompute")` to be true.  But, we don't need to add this.  Thoughts?  It's late, and I can't think.
Also, I'm not 100% sold on this PR, but I think it will be handy during the hands-on exploration phase.  I wonder whether this syntax will be used in "hardened" algorithms, or whether there will usually or always be faster recipes (that may not be obvious or as conveniently written) in practice.  I bet there are simple …

Allow boolean objects to be used as value masks

---

graphblas/matrix.py
graphblas/tests/test_matrix.py
graphblas/tests/test_vector.py
graphblas/vector.py

This allows e.g. `A.select(B.S)` and `A.select(C < 5)`.
This is enhancement (4) in #234.
This does not yet optimize e.g. `A.select(A < 4)` into the suitable select operation, but such an optimization is possible (and would probably be straightforward-ish).
Also, we'll want to double-check the recipes regarding masks, accum, etc.  I think maybe if there is no mask but there is an accumulator, then we shouldn't use `replace=True`.

Recipe to perform select with a mask (or bool) argument.

---

graphblas/_ss/descriptor.py
graphblas/_ss/matrix.py
graphblas/_ss/vector.py
graphblas/dtypes.py
graphblas/tests/test_matrix.py
graphblas/tests/test_vector.py

Fixes #200.
The GxB version of these methods is nicer to work with.  This PR still needs docs and probably a little more cleanup and testing.
Is it okay if `x.ss.serialize()` returns a numpy array of uint8, or would bytes be better?  It's easy to do `val.tobytes()`, but this performs a data copy, so I prefer to return a numpy array.
`.ss.deserialize` accepts a numpy array or buffer.

Add SuiteSparse:GraphBLAS (de)serialize

---

graphblas/_ss/matrix.py
graphblas/_ss/vector.py
graphblas/dtypes.py
graphblas/tests/test_dtype.py
graphblas/tests/test_matrix.py
graphblas/tests/test_vector.py

It's surprisingly annoying to convert a numpy dtype to and from a string, but this seems to do the trick and let's us do it safely without `eval`.

Safely deserialize UDT dtypes

---

.pre-commit-config.yaml
graphblas/base.py
graphblas/infix.py
graphblas/mask.py
graphblas/tests/test_mask.py
graphblas/tests/test_matrix.py
graphblas/tests/test_vector.py

Closes #234
These recipes are much faster than the equivalent recipes in the docstrings, but they still aren't hyper-optimized (they're only *semi*-optimized).  As with `.new`, this is structured so that any recipe can be updated if need arises.
Currently, all recipes return structural masks that may be complemented.  It's not required for them to be structural--perhaps it would be better if some were value masks.

Allow masks to be combined with `|` and`&`

---

.readthedocs.yml
docs/env.yml
docs/user_guide/operators.rst

Docs are not building without a config file to specify additional pip-installed items needed by sphinx.

Add .readthedocs.yml config file

---

.github/workflows/test_and_build.yml
graphblas/_ss/descriptor.py
graphblas/_ss/matrix.py
graphblas/_ss/utils.py
graphblas/_ss/vector.py
graphblas/tests/test_matrix.py
graphblas/tests/test_vector.py
setup.py

Add `matrix.ss.reshape` and update to SS:GB 7.2.0
This uses `GxB_Matrix_reshapeDup`. There is also `GxB_Matrix_reshape` that reshape inplace (and is faster) that we may want to expose too.  Not sure how though--`inplace=True`?  Also note that this method returns a new matrix, not an expression.
Also add "zstd" serialization option.

Matrix reshape

---

graphblas/binary/numpy.py
graphblas/dtypes.py
graphblas/monoid/numpy.py
graphblas/semiring/numpy.py

See: https://github.com/numba/numba/issues/8478
Also, clean up `dtypes` namespace while we're at it.

Fix CI failures; fmin and fmax changed in numba 0.56.2

---

graphblas/operator.py
graphblas/tests/test_op.py

Remove indexunary and select ops from gb.op namespace. This was an oversight during circular import cleanup.

Resolves #266 IndexUnary and Select in gb.op namespace

---

.github/workflows/test_and_build.yml
setup.py

`python-graphblas` is still compatible with 7.2.0, so it was kept as a min version.

Update to SuiteSparse:GraphBLAS 7.3.0

---

graphblas/core/base.py
graphblas/tests/test_matrix.py
graphblas/tests/test_vector.py

This allows e.g `A << (1, 2, 3)` to assign a scalar to every value.  Before, we required `A[:, :] = (1, 2, 3)`.
I don't think there was any reason I didn't do this before other than I overlooked it.

Be more forgiving when assigning UDT scalar to everything

---

graphblas/dtypes.py
graphblas/tests/test_vector.py

This matches the "nicer" repr we have for array UDTs that we already have, so it should be natural to use.
I'm always a little skeptical when extending what numpy does, but I think this is so much easier and more readable.
Quick: can you create a valid numpy array dtype from memory?

Allow easier array UDTs, such as `"INT64[3, 3]"`

---

graphblas/core/ss/matrix.py
graphblas/core/ss/vector.py
graphblas/tests/test_matrix.py
graphblas/tests/test_vector.py

Oops. Previously, we would only call `GxB_Iterator_free` after iterating through everything. Now we call that whenever the generator ends.

Always free SuiteSparse iterator when generator exits

---

graphblas/core/automethods.py
graphblas/core/infix.py
graphblas/core/matrix.py
graphblas/core/ss/matrix.py
graphblas/tests/test_matrix.py

Closes #297 
This will also make it easier to support vanilla GraphBLAS (#307). For example, converting between awkward array can use this API.

Add e.g. `from_dcsr` and `to_dcsc`

---

graphblas/core/infix.py
graphblas/core/matrix.py

This requires changes to both NetworkX and graphblas-algorithms.
Passing a gb.Matrix into a NetworkX algorithm will now trigger the plugin behavior. No need to wrap the Matrix in a ga.Graph first.

Add __networkx_plugin__ to Matrix and variants

---

graphblas/ss/_core.py
graphblas/tests/test_ss_utils.py
setup.py

This adds `gb.ss.about["openmp"]`, which indicates whether SuiteSparse:GraphBLAS was compiled with openmp enabled.

Update to SuiteSparse:GraphBLAS 7.3.2

---

notebooks/Connected Components -- FastSV.ipynb
notebooks/Example B.1 -- Level BFS.ipynb
notebooks/Example B.3 -- Parent BFS.ipynb
notebooks/Intro to GraphBLAS + SSSP example.ipynb
notebooks/Louvain.ipynb
notebooks/Pagerank Demo.ipynb

Some notebooks could probably stand to benefit from a close readthrough and updated to use more modern `python-graphblas` syntax.

Update notebooks to not use deprecated `gb.io.draw`

---

graphblas/core/matrix.py
graphblas/core/scalar.py
graphblas/core/vector.py
graphblas/tests/test_matrix.py
graphblas/tests/test_scalar.py
graphblas/tests/test_vector.py

I don't know how useful this will be in Python, but including for completeness. I'm not fond of the names "materialize" and "complete", but these are what are in the spec.
I added this as an option to `.wait`, because this functionality probably isn't going to be used that often and I didn't want to make a new method.

Add "complete" option to `wait` methods

---

graphblas/core/base.py
graphblas/core/descriptor.py
graphblas/core/operator.py
graphblas/core/ss/descriptor.py
graphblas/core/ss/matrix.py
graphblas/core/ss/vector.py
graphblas/monoid/numpy.py
graphblas/tests/test_matrix.py
graphblas/tests/test_vector.py

Closes https://github.com/python-graphblas/python-graphblas/issues/290. I've been sitting on this for a couple weeks. It still needs tests and documentation, but everything seems to work.
@jim22k, would you like to take a moment to consider the options of having `foo_rowwise` and `foo_columnwise` methods vs having `foo(order="rowwise")`? Here are the methods for each convention, including `sort_rowwise` as in this PR.
These have `order="rowwise"` keyword argument:
- `Matrix.from_dicts`
- `A.to_dicts`
- `A.ss.flatten`
- `A.ss.reshape`
- `v.ss.reshape`
These use `_rowwise` and `_columnwise` suffix:
- `A.reduce_rowwise`
- `A.ss.scan_rowwise`
- `A.ss.selectk_rowwise`
- `A.ss.compactify_rowwise`
- `A.ss.sort_rowwise`
Why not `A.ss.flatten_rowwise` and `A.ss.flatten_columnwise`?
What do we …

Add GxB sort methods

---

graphblas/core/mask.py
graphblas/tests/test_matrix.py

This resolves deprecation of `.mask` mentioned in https://github.com/python-graphblas/python-graphblas/issues/330.

Remove the fully deprecated `.mask` property of `Mask`

---

graphblas/core/ss/matrix.py
graphblas/core/ss/vector.py
graphblas/tests/test_matrix.py

These have been deprecated since 2022-04-04 (see #330)

Remove deprecated `Matrix.ss.diag` and `Vector.ss.diag`

---

graphblas/core/ss/matrix.py
graphblas/core/ss/vector.py
graphblas/core/utils.py

NumPy 1.24 deprecates `np.bool8`, which is an alias of `np.bool_`:
https://numpy.org/devdocs/release/1.24.0-notes.html#np-str0-and-similar-are-now-deprecated

Use `np.bool_` instead of `np.bool8`, which is deprecated

---

.pre-commit-config.yaml
environment.yml

These dependencies aren't typically needed, so I don't want to always install them. But, I want a convenient way to to make environments with some or all of these dependencies, so let's add them commented out by default. I would say these are for advanced users/devs, so I don't want to bother with breaking these up into logical groups (somebody else is welcome to do so). Presumably, if you uncomment an extra dependency to install, you should know why you want it.
@jim22k @SultanOrazbayev is there anything else you would want in one of your dev environments? I think having this section lets us be more accommodating without being overly scrutinizing.
Happy to answer questions for why I added what I did.

Add extra (and not by default) dev dependencies to environment.yml

---

.github/workflows/test_and_build.yml
graphblas/__init__.py
graphblas/core/ss/config.py
graphblas/core/ss/descriptor.py
graphblas/core/ss/matrix.py
graphblas/core/ss/vector.py
graphblas/ss/_core.py
setup.py

I did the easy thing and mapped existing ctypes to `int32_t` when appropriate rather than update data structures on e.g. `MatrixConfig`.
Removing `vararg` should allow `python-graphblas` to be used across more architectures without worry.
I want to get this merged and then do a release.
Reviews welcome, but not necessary imho.

Remove use of `vararg` for increased compatibility

---

graphblas/core/ss/descriptor.py
graphblas/tests/test_matrix.py

Show list of valid descriptor options if bad option is given, or valid values if bad value is given. This follows our long-standing goal of trying to have informative error message to help direct users to proper usage.
This doesn't yet explain the options. It would be nice to be able to point to a docs page for information.

Give informative errors with bad descriptor options

---

.readthedocs.yml
docs/api_reference/index.rst
docs/env.yml
docs/user_guide/udf.rst
environment.yml
graphblas/core/matrix.py
graphblas/core/vector.py
setup.cfg

Also, a few fixes (one warning left to test CI).
If docs are built via `python setup.py build_sphinx`, then warnings will be treated as errors.

Make readthedocs fail if there's a warning building the docs

---

.github/workflows/test_and_build.yml
.pre-commit-config.yaml
conftest.py
graphblas/core/operator.py
graphblas/tests/conftest.py
graphblas/tests/test_numpyops.py
graphblas/tests/test_op.py
pyproject.toml

Randomize Python version and from where to install `python-suitesparse-graphblas`.
The full matrix is over what is more important: that all tests (slow tests, notebooks, etc.) are run on all OSes. This should ensure that our code coverage doesn't fluctuate based on random chance (as it currently does), which will help us achieve and _enforce_ 100% code coverage (#355).
We actually don't have a strong dependence on Python version and the source of `python-suitesparse-graphblas`, so it makes more sense to randomize on those. We still want to test them though, so randomizing makes the most sense imho.
I consolidated the logic of what is installed by conda (_ahem_, mamba). This simplifies the CI config overall, but it makes for a pretty large `mamba install` statement (which we'll be able to …

Change CI matrix to be [os]x[slowtask]

---

.github/workflows/test_and_build.yml
graphblas/core/utils.py

As we discussed in todays meeting, we don't want to run (or require) PyLint to run in CI.
`pylint` is very slow to run, and we have other code formatters and linters that do 99% of things we want. It should be sufficient for somebody to run `pylint` locally every once in a while (such as yearly) to check for minor stylistic issues.
We now have 9 main CI jobs (down from 12) :tada:

Don't run PyLint in CI

---

.github/workflows/test_and_build.yml

Someday the GraphBLAS spec and SuiteSparse:GraphBLAS may be more stable in a way that lets us _easily_ support multiple versions of `python-suitesparse-graphblas`, so might as well set up testing random versions of `psg` too.

Also randomly test `python-suitesparse-graphblas` versions

---

.github/workflows/publish_pypi.yml
pyproject.toml

This is to support editable installs with the new way of doing things:
https://setuptools.pypa.io/en/latest/history.html#v64-0-0

Require setuptools>=64 for build backend

---

.pre-commit-config.yaml
graphblas/core/matrix.py
graphblas/core/operator.py
graphblas/core/vector.py
graphblas/tests/test_infix.py
graphblas/tests/test_matrix.py
graphblas/tests/test_vector.py
pyproject.toml

This was deprecated on 2022-05-23, so we could have actually removed it in 2023.1.0.

Remove deprecated `require_monoid`

---

graphblas/tests/test_op.py
graphblas/unary/__init__.py
pyproject.toml

Deprecated `unary.position` points to `indexunary.rowindex`

---

graphblas/core/operator.py
graphblas/tests/test_op.py
pyproject.toml

Closes #387 
I'm going to want to use this property in `graphblas-algorithms`.

Add `op.is_idempotent` property to Monoids that means `op(x, x) == x`

---

graphblas/io.py
graphblas/tests/test_io.py
graphblas/tests/test_numpyops.py

Note that we now maintain a list of active deprecations on our wiki:
https://github.com/python-graphblas/python-graphblas/wiki/Active-deprecations

Remove expired deprecation of using scipy matrix

---

.github/workflows/test_and_build.yml
.pre-commit-config.yaml
README.md
docs/user_guide/io.rst
environment.yml
graphblas/core/operator.py
graphblas/dtypes.py
graphblas/io.py
graphblas/tests/test_core.py
graphblas/tests/test_dtype.py
graphblas/tests/test_io.py
graphblas/viz.py
notebooks/Louvain.ipynb
pyproject.toml
scripts/check_versions.sh

This contains a few miscellaneous changes including from #391:
- Remove use of `from_numpy` and `to_numpy` in documentation
- Some linting (ruff and pylint)
- Test that complex dtypes are supported when expected
- Handle spurious `DeprecationWarning` from `sparse` 0.14
- `to_pydata_sparse(v)` returns a 1d array (was 2d with shape `(1, n)`)
These are probably the final changes before the next release.

Remove use of `from_numpy` and misc updates/cleanup

---

pyproject.toml

As seen in #397.
This deprecation warning was introduced just yesterday. I guess this means our strictness regarding warnings and randomized testing is working as intended, right?

Handle deprecation warning added in setuptools v67.5.0

---

docs/_static/custom.css
docs/conf.py
docs/env.yml

Our logo just disappeared in the docs. Adding `_static/` to the path seems to fix it. Is `html_static_path` supposed to do this for us?
Reported here: https://github.com/python-graphblas/python-graphblas/issues/396#issuecomment-1458955342
Maybe we should pin to a specific version of `pydata-sphinx-theme`.

Fix path to logo in docs (include `_static` in path)

---

.pre-commit-config.yaml
environment.yml
graphblas/core/expr.py
graphblas/core/formatting.py
graphblas/core/infix.py
graphblas/core/recorder.py
graphblas/tests/test_infix.py
pyproject.toml

Previously, `infixexpr._value` was sometimes `MatrixExpression` and sometimes `Matrix`. Scary!
Fixes #416.

Fix infix expression `_value` and `_expr` usage

---

graphblas/core/operator.py
graphblas/monoid/numpy.py

Import times regressed in #388. This PR fixes it.
A nice way to visualize import times is with https://github.com/nschloe/tuna
Now, as before, import times are dominated by numba and numpy.
I looked at timing for "Test Imports" Github Actions to identify what caused the regression:
https://github.com/python-graphblas/python-graphblas/actions/workflows/imports.yml

Improve import times

---

.pre-commit-config.yaml
MANIFEST.in
README.md
docs/_static/img/logo-name-medium.svg

Small changes to try to make the README more attractive.
I made a new version of the "python-graphblas" logo that is twice as large and hopefully looks okay in both dark and light mode.
I added images of a graph and the corresponding adjacency matrix as shown by our notebook repr.
I added these images to MANIFEST so they will show on PyPI.
I link to `graphblas-algorithms`.
I broke the badges up into three lines.
And, finally, I'm playing around with https://pre-commit.ci which may be able to replace our lint CI action.

Add logo and images to README

---

docs/contributor_guide/index.rst

The previous version did not use the correct syntax for conda environment creation from file.

doc: add missing CLI keyword.

---

.github/workflows/test_and_build.yml
graphblas/tests/test_io.py
pyproject.toml

Fixes #465. Investigated in #466.
Numpy 1.25 is still pretty new. It would be best if somebody could understand and isolate the error to report upstream to `awkward`. I'm also fine hoping later versions of `awkward` "magically" fix this.

xfail awkward tests when using numpy 1.25

---

.pre-commit-config.yaml
graphblas/core/scalar.py
graphblas/core/ss/config.py
graphblas/core/utils.py
graphblas/dtypes/__init__.py
graphblas/tests/test_scalar.py
scripts/check_versions.sh

I noticed `Scalar.__index__` wasn't quite correct. It should be strict and not work for float dtypes.
Also, update how we check whether inputs are integral or not.
Also, update versions.

Allow `__index__` only for integral dtypes on Scalars

---

graphblas/core/ss/matrix.py
graphblas/tests/test_matrix.py

These were deprecated in `2022.11.1`: https://github.com/python-graphblas/python-graphblas/releases/tag/2022.11.1

Remove deprecated `{scan,selectk,compactify}_{row,column}wise`

---

docs/getting_started/primer.rst

updated a link to graphblas.org in the primer to point to the correct address.

fixing broken link to graphblas.org

---

docs/_static/matrix.css
docs/conf.py
docs/user_guide/io.rst
docs/user_guide/operations.rst
docs/user_guide/operators.rst
docs/user_guide/udf.rst

Add a `matrix` style to the stylesheet that formats a table to look like a matrix.
Heavily based on the style used by [matrepr](https://github.com/alugowski/matrepr), but with some tweaks to make it work within the Sphinx/Bootstrap styles.
Add a
```rst
:class: matrix
````
directive to any table. This is stackable with other classes, for example `:class: inline matrix` includes both inline and matrix styles.
If the matrix has row indices, then also add `:stub-columns: 1` to mark the leftmost column as a header. This way the leftmost column is styled as indices, but more importantly the matrix border will be in the correct place (i.e. the indices are outside the matrix).
Example:
```rst
.. csv-table:: A
:class: inline matrix
:header: ,0,1,2,3
:stub-columns: 1
```
Becomes
Closes #496

DOC: add a matrix style

---

.github/workflows/test_and_build.yml
README.md

coveralls has served us well, but it is growing to be a pain. Let's just use codecov instead, which is much more popular among Python libraries that I know.

Drop coveralls (use codecov instead)

---

.codecov.yml
.github/workflows/test_and_build.yml
.pre-commit-config.yaml
graphblas/core/operator/base.py
graphblas/core/operator/binary.py
graphblas/core/operator/indexunary.py
graphblas/core/operator/select.py
graphblas/core/operator/unary.py
graphblas/core/ss/binary.py
graphblas/core/ss/indexunary.py
graphblas/core/ss/select.py
graphblas/core/ss/unary.py
graphblas/tests/test_op.py
graphblas/tests/test_ssjit.py

Also:
- allow a SS JIT function to be registered under the same name with different input types
- be extra-strict about input types for SS JIT
- test numba JIT with select with udt
CC @michelp in case you want to look at the docstrings and signatures of our functions for using SuiteSparse:GraphBLAS JIT such as `gb.binary.ss.register_new`--I think you're the most likely to show off something cool using the JIT ;)
(also, let me know if you want help using the JIT locally).
I think we should cut a new release after this is merged.

Add docstrings for using SS JIT, and make better

---

graphblas/ss/__init__.py

The SuiteSparse:GraphBLAS burble can be pretty handy, and having a burble object makes it as easy to use as possible. We reuse `burble` from python-suitesparse-graphblas (added last year), which is already pretty capable:
https://github.com/GraphBLAS/python-suitesparse-graphblas/blob/decaf1502d1a6053ba7b829e61b5ed796139ff2a/suitesparse_graphblas/__init__.py#L223
Note that one can still interact with the burble via config option such as
```python
gb.ss.config["burble"] = True
```
but sometimes you just want to do
```python
with gb.ss.burble:
...
```
FYI @michelp

Add `gb.ss.burble` from python-suitesparse-graphblas

---

graphblas/__init__.py
graphblas/tests/test_core.py
scripts/test_imports.sh

`INDEX_MAX` may be a nice global value to expose. The GraphBLAS spec doesn't have many of these globals.
This is the largest index value, not the size of the domain of indices. For example, create the largest vector via `Vector(int, INDEX_MAX + 1)`. Also, note that the spec does not specify a value for `GrB_INDEX_MAX`, only that implementations define it, so it may be backend-dependent.
Alternatively, we could instead define `MAX_SIZE`, which would be `GrB_INDEX_MAX + 1`. I think this is much more natural to use; e.g., `Matrix(int, MAX_SIZE, MAX_SIZE)`. I don't think we need both `INDEX_MAX` and `MAX_SIZE`.
So, which to y'all prefer, `INDEX_MAX` or `MAX_SIZE`? Feel free to suggest different names too. 
CC @michelp @jim22k @SultanOrazbayev

Add `gb.MAX_SIZE`, which is `GrB_INDEX_MAX + 1`

---

.pre-commit-config.yaml
graphblas/core/matrix.py
graphblas/tests/test_matrix.py

CC @michelp who requested this.
When n=0, I decided to create a complete diagonal matrix using the identity of the binaryop if the identity exists (and raise if it doesn't).
We want the following equality to hold:
```python
I = A.power(0, semiring)
semiring(I @ A @ I).isequal(A)
```
We could try to make the diagonal more sparse to better support hypersparse matrices, but this would need to determine both nonempty rows and nonempty columns, because `I` needs to be able to be the left-identity and the right-identity. Creating the complete diagonal matrix is much simpler.
CC @jim22k. When we added `Matrix.power` in #483, I believe we discussed `n=0`, and we decided to punt until it was needed. As we discussed, n=0 is a little awkward b/c the identity value isn't always available (since it …

Support `A.power(0)`

---

graphblas/core/automethods.py
graphblas/core/infix.py
graphblas/core/matrix.py
graphblas/core/vector.py
graphblas/tests/test_matrix.py
graphblas/tests/test_vector.py

These have been deprecated since 2022-11-16, so it's been over a year. We wanted to give these a longer deprecation cycle to allow people to swith to `to_coo` and `from_coo`, but I think it's time to clean up.

Remove deprecated `to_values` and `from_values`.
